server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23lioYZLNGb7JMTxWz
            client-secret: e93ae23e61729d9f8472d91914c6c12b478a31e3
            scope: read:user
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
